// Code generated by protoc-gen-go. DO NOT EDIT.
// source: math_message.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Sum struct {
	A                    float32  `protobuf:"fixed32,1,opt,name=a,proto3" json:"a,omitempty"`
	B                    float32  `protobuf:"fixed32,2,opt,name=b,proto3" json:"b,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sum) Reset()         { *m = Sum{} }
func (m *Sum) String() string { return proto.CompactTextString(m) }
func (*Sum) ProtoMessage()    {}
func (*Sum) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4b040cf9c3836a8, []int{0}
}

func (m *Sum) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sum.Unmarshal(m, b)
}
func (m *Sum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sum.Marshal(b, m, deterministic)
}
func (m *Sum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sum.Merge(m, src)
}
func (m *Sum) XXX_Size() int {
	return xxx_messageInfo_Sum.Size(m)
}
func (m *Sum) XXX_DiscardUnknown() {
	xxx_messageInfo_Sum.DiscardUnknown(m)
}

var xxx_messageInfo_Sum proto.InternalMessageInfo

func (m *Sum) GetA() float32 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *Sum) GetB() float32 {
	if m != nil {
		return m.B
	}
	return 0
}

type NewSumRequest struct {
	Sum                  *Sum     `protobuf:"bytes,1,opt,name=sum,proto3" json:"sum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewSumRequest) Reset()         { *m = NewSumRequest{} }
func (m *NewSumRequest) String() string { return proto.CompactTextString(m) }
func (*NewSumRequest) ProtoMessage()    {}
func (*NewSumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4b040cf9c3836a8, []int{1}
}

func (m *NewSumRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewSumRequest.Unmarshal(m, b)
}
func (m *NewSumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewSumRequest.Marshal(b, m, deterministic)
}
func (m *NewSumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewSumRequest.Merge(m, src)
}
func (m *NewSumRequest) XXX_Size() int {
	return xxx_messageInfo_NewSumRequest.Size(m)
}
func (m *NewSumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewSumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewSumRequest proto.InternalMessageInfo

func (m *NewSumRequest) GetSum() *Sum {
	if m != nil {
		return m.Sum
	}
	return nil
}

type NewSumResponse struct {
	Result               float32  `protobuf:"fixed32,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewSumResponse) Reset()         { *m = NewSumResponse{} }
func (m *NewSumResponse) String() string { return proto.CompactTextString(m) }
func (*NewSumResponse) ProtoMessage()    {}
func (*NewSumResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4b040cf9c3836a8, []int{2}
}

func (m *NewSumResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewSumResponse.Unmarshal(m, b)
}
func (m *NewSumResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewSumResponse.Marshal(b, m, deterministic)
}
func (m *NewSumResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewSumResponse.Merge(m, src)
}
func (m *NewSumResponse) XXX_Size() int {
	return xxx_messageInfo_NewSumResponse.Size(m)
}
func (m *NewSumResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewSumResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewSumResponse proto.InternalMessageInfo

func (m *NewSumResponse) GetResult() float32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type FibonacciRequest struct {
	Number               int32    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FibonacciRequest) Reset()         { *m = FibonacciRequest{} }
func (m *FibonacciRequest) String() string { return proto.CompactTextString(m) }
func (*FibonacciRequest) ProtoMessage()    {}
func (*FibonacciRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4b040cf9c3836a8, []int{3}
}

func (m *FibonacciRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FibonacciRequest.Unmarshal(m, b)
}
func (m *FibonacciRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FibonacciRequest.Marshal(b, m, deterministic)
}
func (m *FibonacciRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FibonacciRequest.Merge(m, src)
}
func (m *FibonacciRequest) XXX_Size() int {
	return xxx_messageInfo_FibonacciRequest.Size(m)
}
func (m *FibonacciRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FibonacciRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FibonacciRequest proto.InternalMessageInfo

func (m *FibonacciRequest) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type FibonacciResponse struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FibonacciResponse) Reset()         { *m = FibonacciResponse{} }
func (m *FibonacciResponse) String() string { return proto.CompactTextString(m) }
func (*FibonacciResponse) ProtoMessage()    {}
func (*FibonacciResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4b040cf9c3836a8, []int{4}
}

func (m *FibonacciResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FibonacciResponse.Unmarshal(m, b)
}
func (m *FibonacciResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FibonacciResponse.Marshal(b, m, deterministic)
}
func (m *FibonacciResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FibonacciResponse.Merge(m, src)
}
func (m *FibonacciResponse) XXX_Size() int {
	return xxx_messageInfo_FibonacciResponse.Size(m)
}
func (m *FibonacciResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FibonacciResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FibonacciResponse proto.InternalMessageInfo

func (m *FibonacciResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*Sum)(nil), "fullcycle.Sum")
	proto.RegisterType((*NewSumRequest)(nil), "fullcycle.NewSumRequest")
	proto.RegisterType((*NewSumResponse)(nil), "fullcycle.NewSumResponse")
	proto.RegisterType((*FibonacciRequest)(nil), "fullcycle.FibonacciRequest")
	proto.RegisterType((*FibonacciResponse)(nil), "fullcycle.FibonacciResponse")
}

func init() { proto.RegisterFile("math_message.proto", fileDescriptor_b4b040cf9c3836a8) }

var fileDescriptor_b4b040cf9c3836a8 = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0x86, 0x71, 0x4a, 0x23, 0xf5, 0x0a, 0x15, 0xdc, 0x50, 0x85, 0xc2, 0x50, 0x3c, 0x55, 0x20,
	0x45, 0x50, 0x56, 0x26, 0x06, 0x06, 0x24, 0x18, 0x92, 0x8d, 0x05, 0xd9, 0xd6, 0x41, 0x23, 0xc5,
	0x49, 0x88, 0x6d, 0x10, 0xbf, 0x84, 0xbf, 0x8b, 0xf2, 0xa9, 0x50, 0x65, 0x7c, 0x75, 0x8f, 0x9f,
	0xf7, 0x4e, 0x06, 0xd4, 0xc2, 0xee, 0xde, 0x34, 0x19, 0x23, 0x3e, 0x28, 0x2c, 0xca, 0xdc, 0xe6,
	0x38, 0x7b, 0x77, 0x69, 0xaa, 0x7e, 0x54, 0x4a, 0xfc, 0x12, 0x26, 0xb1, 0xd3, 0x78, 0x04, 0x4c,
	0x04, 0x6c, 0xcd, 0x36, 0x5e, 0xc4, 0x44, 0x95, 0x64, 0xe0, 0x35, 0x49, 0xf2, 0x5b, 0x38, 0x7e,
	0xa1, 0xef, 0xd8, 0xe9, 0x88, 0x3e, 0x1d, 0x19, 0x8b, 0x6b, 0x98, 0x18, 0xa7, 0x6b, 0x7c, 0xbe,
	0x5d, 0x84, 0xbd, 0x2c, 0xac, 0x98, 0x6a, 0xc4, 0x37, 0xb0, 0xe8, 0x9e, 0x98, 0x22, 0xcf, 0x0c,
	0xe1, 0x12, 0xfc, 0x92, 0x8c, 0x4b, 0x6d, 0xdb, 0xd2, 0x26, 0x7e, 0x05, 0x27, 0x8f, 0x89, 0xcc,
	0x33, 0xa1, 0x54, 0xd2, 0xf9, 0x97, 0xe0, 0x67, 0x4e, 0x4b, 0x2a, 0x6b, 0x76, 0x1a, 0xb5, 0x89,
	0x5f, 0xc3, 0xe9, 0x80, 0x1d, 0x15, 0x4f, 0x3b, 0xf1, 0xf6, 0x97, 0xc1, 0xfc, 0x59, 0xd8, 0x5d,
	0x4c, 0xe5, 0x57, 0xa2, 0x08, 0xef, 0x9b, 0x43, 0x83, 0xc1, 0xba, 0xff, 0xae, 0x5a, 0x9d, 0x8d,
	0x4c, 0x9a, 0x0e, 0x7e, 0x80, 0x4f, 0x30, 0xeb, 0xab, 0xf1, 0x7c, 0x40, 0xee, 0x2f, 0xbf, 0xba,
	0x18, 0x1f, 0x76, 0xa6, 0x1b, 0xf6, 0x70, 0xf8, 0xea, 0x15, 0x52, 0xfa, 0xf5, 0x57, 0xdc, 0xfd,
	0x05, 0x00, 0x00, 0xff, 0xff, 0x44, 0x82, 0xa6, 0x6b, 0xa0, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MathServiceClient is the client API for MathService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MathServiceClient interface {
	Sum(ctx context.Context, in *NewSumRequest, opts ...grpc.CallOption) (*NewSumResponse, error)
	Fibonacci(ctx context.Context, in *FibonacciRequest, opts ...grpc.CallOption) (MathService_FibonacciClient, error)
}

type mathServiceClient struct {
	cc *grpc.ClientConn
}

func NewMathServiceClient(cc *grpc.ClientConn) MathServiceClient {
	return &mathServiceClient{cc}
}

func (c *mathServiceClient) Sum(ctx context.Context, in *NewSumRequest, opts ...grpc.CallOption) (*NewSumResponse, error) {
	out := new(NewSumResponse)
	err := c.cc.Invoke(ctx, "/fullcycle.MathService/Sum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mathServiceClient) Fibonacci(ctx context.Context, in *FibonacciRequest, opts ...grpc.CallOption) (MathService_FibonacciClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MathService_serviceDesc.Streams[0], "/fullcycle.MathService/Fibonacci", opts...)
	if err != nil {
		return nil, err
	}
	x := &mathServiceFibonacciClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MathService_FibonacciClient interface {
	Recv() (*FibonacciResponse, error)
	grpc.ClientStream
}

type mathServiceFibonacciClient struct {
	grpc.ClientStream
}

func (x *mathServiceFibonacciClient) Recv() (*FibonacciResponse, error) {
	m := new(FibonacciResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MathServiceServer is the server API for MathService service.
type MathServiceServer interface {
	Sum(context.Context, *NewSumRequest) (*NewSumResponse, error)
	Fibonacci(*FibonacciRequest, MathService_FibonacciServer) error
}

// UnimplementedMathServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMathServiceServer struct {
}

func (*UnimplementedMathServiceServer) Sum(ctx context.Context, req *NewSumRequest) (*NewSumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sum not implemented")
}
func (*UnimplementedMathServiceServer) Fibonacci(req *FibonacciRequest, srv MathService_FibonacciServer) error {
	return status.Errorf(codes.Unimplemented, "method Fibonacci not implemented")
}

func RegisterMathServiceServer(s *grpc.Server, srv MathServiceServer) {
	s.RegisterService(&_MathService_serviceDesc, srv)
}

func _MathService_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewSumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MathServiceServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fullcycle.MathService/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MathServiceServer).Sum(ctx, req.(*NewSumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MathService_Fibonacci_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FibonacciRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MathServiceServer).Fibonacci(m, &mathServiceFibonacciServer{stream})
}

type MathService_FibonacciServer interface {
	Send(*FibonacciResponse) error
	grpc.ServerStream
}

type mathServiceFibonacciServer struct {
	grpc.ServerStream
}

func (x *mathServiceFibonacciServer) Send(m *FibonacciResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _MathService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fullcycle.MathService",
	HandlerType: (*MathServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sum",
			Handler:    _MathService_Sum_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Fibonacci",
			Handler:       _MathService_Fibonacci_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "math_message.proto",
}
